test cd

diff --git a/.github/workflows/auth-ms-cicd.yml b/.github/workflows/auth-ms-cicd.yml
--- a/.github/workflows/auth-ms-cicd.yml
+++ b/.github/workflows/auth-ms-cicd.yml
@@ -8,119 +8,119 @@ on:
       
 
 jobs:
-  vulnerability-check:
-    runs-on: ubuntu-latest  
-    steps:
-      - uses: actions/checkout@v3 
+  # vulnerability-check:
+  #   runs-on: ubuntu-latest  
+  #   steps:
+  #     - uses: actions/checkout@v3 
         
-      - name: Setup Go environment
-        uses: actions/setup-go@v3
-        with:
-          go-version: 1.22.3
+  #     - name: Setup Go environment
+  #       uses: actions/setup-go@v3
+  #       with:
+  #         go-version: 1.22.3
       
-      - name: Install dependencies
-        run: cd auth-ms && go mod tidy
+  #     - name: Install dependencies
+  #       run: cd auth-ms && go mod tidy
 
-      - name: Get official govulncheck
-        run: go install golang.org/x/vuln/cmd/govulncheck@latest
-        shell: bash
+  #     - name: Get official govulncheck
+  #       run: go install golang.org/x/vuln/cmd/govulncheck@latest
+  #       shell: bash
 
-      - name: Run govulncheck
-        run: cd auth-ms && govulncheck -show verbose .
-        shell: bash    
+  #     - name: Run govulncheck
+  #       run: cd auth-ms && govulncheck -show verbose .
+  #       shell: bash    
         
-      - name: Get golangci-lint
-        run: |
-          curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.59.0
-          chmod +x ./bin/golangci-lint
-        shell: bash
+  #     - name: Get golangci-lint
+  #       run: |
+  #         curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.59.0
+  #         chmod +x ./bin/golangci-lint
+  #       shell: bash
 
-      - name: Run Static Test
-        run: cd auth-ms && ../bin/golangci-lint run 
+  #     - name: Run Static Test
+  #       run: cd auth-ms && ../bin/golangci-lint run 
           
-  build:
-    needs: vulnerability-check
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v3 
-      - name: Add environment variables
-        run: |
-          cd auth-ms && touch .env && echo 'MONGODB_URI=${{secrets.DB_HOST}}' >> .env && echo 'JWT_SECRET=${{secrets.JWT_SECRET}}' >> .env && echo 'DB_NAME=${{secrets.DB_NAME}}' >> .env && cat .env
-      - name: Build
-        run: cd auth-ms && go build -o auth-ms-build .
-      - name: Upload artifact
-        uses: actions/upload-artifact@v3
-        with:
-          name: build-artifact
-          path: auth-ms  
+  # build:
+  #   needs: vulnerability-check
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: actions/checkout@v3 
+  #     - name: Add environment variables
+  #       run: |
+  #         cd auth-ms && touch .env && echo 'MONGODB_URI=${{secrets.DB_HOST}}' >> .env && echo 'JWT_SECRET=${{secrets.JWT_SECRET}}' >> .env && echo 'DB_NAME=${{secrets.DB_NAME}}' >> .env && cat .env
+  #     - name: Build
+  #       run: cd auth-ms && go build -o auth-ms-build .
+  #     - name: Upload artifact
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         name: build-artifact
+  #         path: auth-ms  
   
-  test:
-    needs: build
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v3
-      - name: Download build artifact
-        uses: actions/download-artifact@v3
-        with:
-          name: build-artifact
-          path: auth-ms-build   
-      - name: Test
-        run: |
-          cd auth-ms-build
-          if ! go test; then
-            echo "Tests failed, stopping workflow."
-            exit 1
-          fi
+  # test:
+  #   needs: build
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: actions/checkout@v3
+  #     - name: Download build artifact
+  #       uses: actions/download-artifact@v3
+  #       with:
+  #         name: build-artifact
+  #         path: auth-ms-build   
+  #     - name: Test
+  #       run: |
+  #         cd auth-ms-build
+  #         if ! go test; then
+  #           echo "Tests failed, stopping workflow."
+  #           exit 1
+  #         fi
 
-      - name: Upload code coverage report to Codecov
-        uses: codecov/codecov-action@v2
-        with:
-          token: ${{ secrets.CODECOV_TOKEN }}
+  #     - name: Upload code coverage report to Codecov
+  #       uses: codecov/codecov-action@v2
+  #       with:
+  #         token: ${{ secrets.CODECOV_TOKEN }}
 
-      - name: Check Codecov report for errors
-        run: |
-          if [ -f codecov.txt ]; then
-            if grep -q 'error' codecov.txt; then
-              echo "Error found in Codecov report, stopping workflow."
-              exit 1
-            fi
-          fi
+  #     - name: Check Codecov report for errors
+  #       run: |
+  #         if [ -f codecov.txt ]; then
+  #           if grep -q 'error' codecov.txt; then
+  #             echo "Error found in Codecov report, stopping workflow."
+  #             exit 1
+  #           fi
+  #         fi
   
-  build-and-deliver-docker-image:
-    runs-on: ubuntu-latest
-    needs: test
-    steps:
-      - name: Checkout code 
-        uses: actions/checkout@v3
+  # build-and-deliver-docker-image:
+  #   runs-on: ubuntu-latest
+  #   needs: test
+  #   steps:
+  #     - name: Checkout code 
+  #       uses: actions/checkout@v3
         
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
+  #     - name: Set up Docker Buildx
+  #       uses: docker/setup-buildx-action@v3
         
-      - name: Build image
-        run: cd auth-ms && docker build -t auth-ms:latest .
+  #     - name: Build image
+  #       run: cd auth-ms && docker build -t auth-ms:latest .
 
-      - name: Container Security Scanning
-        run: |
-          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image auth-ms:latest
-          if [ $? -ne 0 ]; then
-            echo "Security vulnerabilities found, stopping workflow."
-            exit 1
-          fi
+  #     - name: Container Security Scanning
+  #       run: |
+  #         docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image auth-ms:latest
+  #         if [ $? -ne 0 ]; then
+  #           echo "Security vulnerabilities found, stopping workflow."
+  #           exit 1
+  #         fi
         
-      - name: Login to Azure Container Registry
-        uses: azure/docker-login@v1
-        with:
-          login-server: pfaacr.azurecr.io
-          username: ${{ secrets.ACR_USERNAME }}
-          password: ${{ secrets.ACR_PASSWORD }}
+  #     - name: Login to Azure Container Registry
+  #       uses: azure/docker-login@v1
+  #       with:
+  #         login-server: pfaacr.azurecr.io
+  #         username: ${{ secrets.ACR_USERNAME }}
+  #         password: ${{ secrets.ACR_PASSWORD }}
 
-      - name: Tag Docker image
-        run: |
-          docker tag auth-ms:latest pfaacr.azurecr.io/auth-ms:latest
+  #     - name: Tag Docker image
+  #       run: |
+  #         docker tag auth-ms:latest pfaacr.azurecr.io/auth-ms:latest
 
-      - name: Push Docker image to ACR
-        run: |
-          docker push pfaacr.azurecr.io/auth-ms:latest 
+  #     - name: Push Docker image to ACR
+  #       run: |
+  #         docker push pfaacr.azurecr.io/auth-ms:latest 
 
   infrastructure-provision:
     runs-on: ubuntu-latest
@@ -177,8 +177,9 @@ jobs:
           creds: ${{secrets.AZURE_CREDENTIALS}} 
       - name: link azure aks with kubernetes
         run: az aks get-credentials --name pfaaks --resource-group pfa
-        #      - name: create a secret for acr and aks
-        #        run: kubectl create secret docker-registry secretpfa --docker-server=pfaacr.azurecr.io --docker-username=${{secrets.ACR_USERNAME}} --docker-password=${{secrets.ACR_PASSWORD}}
+      - name: create a secret for acr and aks
+        run: kubectl create secret docker-registry secretpfa --docker-server=pfaacr.azurecr.io --docker-username=${{secrets.ACR_USERNAME}} --docker-password=${{secrets.ACR_PASSWORD}}
+        continue-on-error: true
       - name: deployment
         run: cd mychart && helm install pfa-chart pfa-chart 
         
