handle errors in workflow tests

diff --git a/.github/workflows/products-ms-cicd.yml b/.github/workflows/products-ms-cicd.yml
--- a/.github/workflows/products-ms-cicd.yml
+++ b/.github/workflows/products-ms-cicd.yml
@@ -28,6 +28,10 @@ jobs:
         run: |
           cd products-ms
           npm audit --json > npm-audit.json
+          if [[ $(< npm-audit.json) != "[]" ]]; then
+            echo "Vulnerabilities found, stopping workflow."
+            exit 1
+          fi
 
       - name: Show NPM Audit Report
         run: |
@@ -40,7 +44,24 @@ jobs:
           PORT: ${{secrets.PRODUCT_MS_PORT}}
         run: |
           cd products-ms
-          npm test
+          if ! npm test; then
+            echo "Tests failed, stopping workflow."
+            exit 1
+          fi
+          
+      - name: Upload code coverage report to Codecov
+        uses: codecov/codecov-action@v2
+        with:
+          token: ${{ secrets.CODECOV_TOKEN }}
+
+      - name: Check Codecov report for errors
+        run: |
+          if [ -f codecov.txt ]; then
+            if grep -q 'error' codecov.txt; then
+              echo "Error found in Codecov report, stopping workflow."
+              exit 1
+            fi
+          fi
 
       - name: Build NestJS app
         run: |
@@ -82,6 +103,10 @@ jobs:
       - name: Container Security Scanning
         run: |
           docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image products-ms:latest
+          if [ $? -ne 0 ]; then
+            echo "Security vulnerabilities found, stopping workflow."
+            exit 1
+          fi
 
       - name: Login to Azure Container Registry ACR
         uses: azure/docker-login@v1
@@ -97,15 +122,3 @@ jobs:
       - name: Push Docker image to ACR
         run: |
           docker push pfaacr.azurecr.io/products-ms:latest
-  codecov:
-    runs-on: ubuntu-latest
-    needs: build-docker-image
-
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
-
-      - name: Upload code coverage report
-        uses: codecov/codecov-action@v2
-        with:
-          token: ${{ secrets.CODECOV_TOKEN }}
